apiVersion: apps/v1
kind: Deployment
metadata:
  name: entity-management-api-deployment
spec:
  template:
    spec:
      containers:
        - name: entity-management-api
          # required to use local image
          imagePullPolicy: Never